---
title: "Employment Time Series"
author: "Faith Ha & "
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
rm(list=ls())
library(TSA)
library(tseries)
library(forecast)
library(lmtest)
library(dplyr)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
getwd()

# read in csv file
employment <- read.csv("employment.csv", header=TRUE)
employment
class(employment) 
head(employment)


# Conversion to Time Series
employment_TS <- ts(employment$employed, start = c(1978, 2), frequency =12)
class(employment_TS)
summary(employment_TS)
plot(employment_TS,type='o',ylab='Employment', main = " Time series plot of Employment by 1000")

# acf and pacf plots
par(mfrow=c(1,2))
acf(employment_TS,lag.max = 98, main ="ACF plot for the Global Temperature Anomalies series.")
pacf(employment_TS, main ="PACF plot for the Global Temperature Anomalies series.")
par(mfrow=c(1,1))
```

``` {r pressure, echo=FALSE}
# qq plot 
qqnorm(employment_TS)
qqline(employment_TS, col = 2)
shapiro.test(employment_TS)


# adf test (weak indicator of non-stationary)
adf.test(employment_TS, alternative = c("stationary")) # Use default value of k

# pp test
pp.test(employment_TS)
kpss.test(employment_TS)

summary(employment_TS)


BC <- BoxCox.ar(employment_TS, lambda = seq(0.5, 1, 0.01))
BC$ci
lambda <- BC$lambda[which(max(BC$loglike) == BC$loglike)]
lambda # lambda = 0.5 corresponds to square root transformation?
# BC.employment = (employment_TS^lambda-1)/lambda

# plot(BC.employment,type='o',ylab='Time series plot of BC transformed 
     # yearly average unemployment numbers.')

sqrt_data <- sqrt(employment_TS)

plot(sqrt_data,type='o',ylab='Time series plot of BC transformed 
     yearly average unemployment numbers.')


par(mfrow=c(1,1))
qqnorm(sqrt_data)
qqline(sqrt_data, col = 2)
shapiro.test(sqrt_data)

par(mfrow=c(1,2))
acf(sqrt_data, main='ACF plot of employment series.')
pacf(sqrt_data, main='PACF plot of employment series.')
par(mfrow=c(1,1))

diff.employment = diff(sqrt_data)

par(mfrow=c(1,1))
plot(diff.employment,type='o',ylab='Average employment numbers', main = "Time series plot of the first differenced
     yearly average employment numbers.")
# There is still some trend in there series
adf.test(diff.employment) # stationary
pp.test(diff.employment) # stationary
kpss.test(diff.employment) # non stationary

```